server:
  port: 2019
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true
  context-path: /
spring:
  mvc:
    view:
      suffix: .html
      prefix: /
    static-path-pattern: /**
  resources:
    static-locations:
      - classpath:/resources/
      - classpath:/static/
      - classpath:/web/
  # REDIS数据源配置
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 0
    pool.max-active: 500
    pool.max-idle: 300
    pool.min-idle: 10
  # MYSQL数据源配置
  datasource:
    url: jdbc:mysql://XXX/2019_ncov?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中# 初始化大小，最小，最大
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      # 检测池里连接的可用性
      test-on-borrow: true
      test-while-idle: true
      test-on-return: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: administrator
        login-password: 2019-administrator
mybatis:
  # MyBatis配置
  type-aliases-package: china.fighting.domain
  mapper-locations: classpath:china/fighting/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  # PageHelper配置
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mapper:
  # MyMapper配置
  mappers: china.fighting.config.MyMapper
  not-empty: false
  identity: MYSQL

# 第三方API-KEY
app:
  api:
    key: